substitutions:
  # General configuration
  clockos_device_friendly_name: "ClockOS"
  clockos_fallback_hotspot_name: "ClockOS Fallback Hotspot"
  clockos_display_platform: ssd1306_i2c
  clockos_display_model: "SSD1306 128x64"


  # GPIO pins
  clockos_pin_beeper: GPIO05
  clockos_pin_rumble_motor: GPIO10
  clockos_pin_display_sda: GPIO03
  clockos_pin_display_scl: GPIO04
  clockos_pin_encoder_a: GPIO02
  clockos_pin_encoder_b: GPIO1


packages:
  # Core
  - !include clockos/packages/globals.yaml
  - !include clockos/packages/core.yaml
  - !include clockos/packages/hardware.yaml
  - !include clockos/packages/graphics.yaml
  - !include clockos/packages/sensors.yaml
  - !include clockos/packages/menu.yaml

  # Features
  - !include clockos/packages/features/alarm.yaml

  # Features
  # - !include clockos/games/snake/snake.yaml

switch:
  - platform: template
    name: "Autoplay"
    id: switch_game_autoplay
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      return id(global_game_autoplay);
    turn_on_action:
      - lambda: 'id(global_game_autoplay) = true;'
    turn_off_action:
      - lambda: 'id(global_game_autoplay) = false;'
  - platform: template
    name: "Sound"
    id: switch_game_sound
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      return id(global_game_sound);
    turn_on_action:
      - lambda: 'id(global_game_sound) = true;'
    turn_off_action:
      - lambda: 'id(global_game_sound) = false;'
  - platform: template
    name: "Rumble"
    id: switch_game_rumble
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      return id(global_game_rumble);
    turn_on_action:
      - lambda: 'id(global_game_rumble) = true;'
    turn_off_action:
      - lambda: 'id(global_game_rumble) = false;'
  - platform: template
    name: "Snake walls"
    id: switch_game_snake_walls
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      return id(global_game_snake_walls);
    turn_on_action:
      - lambda: 'id(global_game_snake_walls) = true;'
    turn_off_action:
      - lambda: 'id(global_game_snake_walls) = false;'
  - platform: homeassistant
    id: switch_wake_up_alarm
    entity_id: input_boolean.wake_up_lights


sensor:
  - platform: homeassistant
    id: ha_temperature
    entity_id: sensor.weather_temperature

  - platform: homeassistant
    id: ha_humidity
    entity_id: weather.forecast_home
    attribute: humidity

number:
  - platform: template
    id: snake_speed
    name: "Speed"
    step: 1
    min_value: 1
    max_value: 20
    optimistic: true
    initial_value: 7
    set_action:
    - lambda: |-
        id(global_game_snake_speed) = (int)x;


graph:
  # Show bare-minimum auto-ranged graph
  - id: wifi_graph
    #duration: 150s
    duration: 60s
    # width: 124
    # height: 28
    width: 124
    height: 16
    traces:
      - sensor: wifi_rssi
        line_thickness: 2
        continuous: True


################################################################
# Display / Pages
################################################################
display:
  - platform: ${clockos_display_platform}
    id: clockos_display
    model: ${clockos_display_model}
    address: 0x3C
    invert: false
    contrast: 50%
    auto_clear_enabled: true
    update_interval: 16ms

    pages:

      - id: page_main
        lambda: !include "clockos/screens/clock.cpp"

      - id: page_system
        lambda: !include "clockos/screens/system.cpp"

      - id: page_demo_spin
        lambda: !include "clockos/games/demos/spin.cpp"

      - id: page_demo_dvd_screen_saver
        lambda: !include "clockos/games/demos/dvd_screen_saver.cpp"

      - id: page_demo_tokyo_bunny
        lambda: !include "clockos/games/demos/tokyo_bunny.cpp"

      - id: page_demo_bunnywiggle
        lambda: !include "clockos/games/demos/bunnywiggle.cpp"

      - id: page_demo_text_input
        lambda: !include "clockos/games/demos/text_input.cpp"

      - id: page_game_breakout
        lambda: !include "clockos/games/breakout.cpp"

      - id: page_game_snake
        lambda: !include "clockos/games/snake.cpp"


# Image assets
image:
  defaults:
    type: BINARY
  images:
    - file: clockos/images/bunnygirl_01.png
      id: image_bunnygirl_01
    - file: clockos/images/bunnygirl_02.png
      id: image_bunnygirl_02
    - file: clockos/images/bunnygirl_03.png
      id: image_bunnygirl_03
    - file: clockos/images/bunnygirl_04.png
      id: image_bunnygirl_04

animation:
  - file: "clockos/images/bunnywiggle_01.gif"
    id: animation_bunnywiggle_01
    type: BINARY
  - file: "clockos/images/bunnywiggle_02.gif"
    id: animation_bunnywiggle_02
    type: BINARY
