substitutions:
  # General configuration
  clockos_device_name: esp32-c3-mini-2
  clockos_device_friendly_name: "ClockOS"
  clockos_fallback_hotspot_name: "ClockOS Fallback Hotspot"
  clockos_ota_password: !secret clockos_ota_password
  clockos_display_platform: ssd1306_i2c
  clockos_display_model: "SSD1306 128x64"

  # GPIO pins
  clockos_pin_beeper: GPIO05
  clockos_pin_rumble_motor: GPIO10
  clockos_pin_display_sda: GPIO03
  clockos_pin_display_scl: GPIO04
  clockos_pin_encoder_a: GPIO02
  clockos_pin_encoder_b: GPIO1
  clockos_pin_encoder_button: GPIO0


sensor:
  - platform: homeassistant
    id: ha_temperature
    entity_id: sensor.weather_temperature

  - platform: homeassistant
    id: ha_humidity
    entity_id: weather.forecast_home
    attribute: humidity

graph:
  # Show bare-minimum auto-ranged graph
  - id: wifi_graph
    duration: 60s
    width: 124
    height: 16
    traces:
      - sensor: wifi_rssi
        line_thickness: 2
        continuous: True

packages:
  # Core
  - !include clockos/packages/globals.yaml
  - !include clockos/packages/core.yaml
  - !include clockos/packages/scripts.yaml
  - !include clockos/packages/hardware.yaml
  - !include clockos/packages/graphics.yaml
  - !include clockos/packages/sensors.yaml
  - !include clockos/packages/menu.yaml

  # Features
  - !include clockos/packages/features/alarm.yaml
  - !include clockos/packages/features/floorplan.yaml
  - !include clockos/packages/features/sounds.yaml
  - !include clockos/packages/features/system.yaml

  # Games
  - !include clockos/packages/games/breakout/breakout.yaml
  - !include clockos/packages/games/snake/snake.yaml

  # Demos
  - !include clockos/packages/demos/dvd_screen_saver/dvd_screen_saver.yaml
  - !include clockos/packages/demos/spin/spin.yaml
  - !include clockos/packages/demos/text_input/text_input.yaml
  - !include clockos/packages/demos/tokyo_bunny/tokyo_bunny.yaml
  - !include clockos/packages/demos/bunny_wiggle/bunny_wiggle.yaml
