esp32:
  board: ${clockos_board}
  # Tested on: esp32-c3-devkitm-1, esp32doit-devkit-v1
  framework:
    type: ${clockos_framework_type}


esphome:
  name: ${clockos_device_name}
  friendly_name: ${clockos_device_friendly_name}
  on_boot:
    then:
      # Show main clock page on boot
      - display.page.show: page_main

      # The knob position needs to be initialized on boot, otherwise the value is unpredictable
      # It is set here to a mid-point value (max is 50)
      - lambda: |-
          id(clockos_knob).publish_state(25);

      # Initialize display brightness
      - number.set:
          id: clockos_number_display_brightness
          value: !lambda "return int(id(clockos_global_display_brightness));"

      # Initialize display timeout
      - number.set:
          id: clockos_number_display_timeout
          value: !lambda "return id(clockos_global_display_timeout) / 60;"

      # Start display activity check loop
      - script.execute: script_display_activity_check_loop


# Enable Home Assistant API
api:
  encryption:
    key: !secret clockos_api_key
  reboot_timeout: 0s # Disable API connection-loss reboot


# Enable Over-the-Air updates
ota:
  - platform: esphome
    password: ${clockos_ota_password}


# Enable WiFi
wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_fallback_ssid
      password: !secret wifi_fallback_password
  id: wifi0
  reboot_timeout: 0s # Disable WiFi connection-loss reboot

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${clockos_fallback_hotspot_name}
    password: !secret clockos_fallback_hotspot_password


# Fallback WiFi portal
captive_portal:
  id: clockos_captive_portal


# Enable logging
logger:
  level: INFO  # Disable Debug logging 
  logs:
    graph: ERROR


# Log level selector
select:
  - platform: logger
    name: "Log level"


# Restart button
button:
  - platform: restart
    id: clockos_button_restart
    name: "Restart"


# Time sources
time:
  - platform: sntp
    id: clockos_time_sntp
    on_time:
      - seconds: 0
        then:
          - script.execute: script_check_display_activity
  - platform: homeassistant
    id: clockos_time_ha
    on_time:
      - seconds: 0
        then:
          - script.execute: script_check_display_activity

# Core scripts
script:
  # Workaround to check the display activity periodically, even when no time update events occur (if time can't be synced at all)
  # TODO: This doesn't seem to work in all circumstances
  - id: script_display_activity_check_loop
    mode: restart
    then:
      - lambda: ESP_LOGI("core", "Checking display activity");
      - script.execute: script_check_display_activity
      - delay: 59s
      - script.execute: script_display_activity_check_loop_retrigger
      
  - id: script_display_activity_check_loop_retrigger
    mode: restart
    then:
      - lambda: ESP_LOGI("core", "Retriggering activity check");
      - delay: 1s
      - script.execute: script_display_activity_check_loop

  - id: script_check_display_activity
    then:
      - lambda: |-
          ESP_LOGI("core", "Running script: script_check_display_activity");
          // ESP_LOGI("core", "Running script: script_check_display_activity");
          // Check if the display activity timestamp is older than the timeout setting
          if (
            id(clockos_global_display_timeout) > 0
            && id(clockos_current_timestamp).state - id(clockos_last_activity_timestamp)
               > id(clockos_global_display_timeout)
          ) {
            // Turn off the display after 60 seconds of inactivity
            id(clockos_display).turn_off();
          }
  - id: script_update_last_activity
    then:
      - lambda: |-
          id(clockos_last_activity_timestamp) = id(clockos_current_timestamp).state;
          id(clockos_display).turn_on();


sensor:
  - platform: template
    name: "Current timestamp"
    id: clockos_current_timestamp
    unit_of_measurement: "s"
    icon: "mdi:clock-time-three"
    update_interval: 10s
    lambda: |-
      auto sntp = id(clockos_time_sntp).now();
      if (sntp.is_valid()) {
        return sntp.timestamp;
      }

      auto ha = id(clockos_time_ha).now();
      if (ha.is_valid()) {
        return ha.timestamp;
      }

      return NAN;


# Misc settings, probably will move into a package later
switch:
  - platform: template
    name: "Autoplay"
    id: clockos_switch_game_autoplay
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      return id(clockos_global_game_autoplay);
    turn_on_action:
      - lambda: 'id(clockos_global_game_autoplay) = true;'
    turn_off_action:
      - lambda: 'id(clockos_global_game_autoplay) = false;'
