################################################################
# Hardware
################################################################

# Settings
number:
  - platform: template
    id: clockos_number_display_brightness
    name: "Screen Brightness"
    icon: "mdi:brightness-percent"
    step: 5
    min_value: 1
    max_value: 100
    optimistic: true
    initial_value: 50
    set_action:
    - lambda: |-
        id(clockos_display).set_contrast(x / 100.0);
        id(clockos_global_display_brightness) = x;

  - platform: template
    id: clockos_number_display_timeout
    name: "Screen timeout"
    icon: "mdi:power-sleep"
    step: 1
    min_value: 0
    max_value: 60
    optimistic: true
    initial_value: 0
    set_action:
    - lambda: |-
        id(clockos_global_display_timeout) = (int)x * 60;

  - platform: template
    id: clockos_number_beeper_volume
    name: "Volume"
    icon: "mdi:speaker"
    step: 5
    min_value: 0
    max_value: 100
    optimistic: true
    initial_value: 2
    set_action:
    - lambda: |-
        id(clockos_rtttl_player).set_gain(x / 100.0);
        id(clockos_global_global_beeper_volume) = (int)x;


################################################################
# Output / Beeper / Rumbble
################################################################
output:
  - platform: ledc
    pin: ${clockos_pin_beeper}
    id: clockos_rtttl_pwm_output

rtttl:
  output: clockos_rtttl_pwm_output
  id: clockos_rtttl_player
  gain: 2%

switch:
  - platform: gpio
    id: clockos_output_rumble
    pin: ${clockos_pin_rumble_motor}
    name: "Rumble Motor"
  - platform: template
    name: "Sound"
    id: clockos_switch_sound_enabled
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      return id(clockos_global_sound_enabled);
    turn_on_action:
      - lambda: 'id(clockos_global_sound_enabled) = true;'
    turn_off_action:
      - lambda: 'id(clockos_global_sound_enabled) = false;'
  - platform: template
    name: "Rumble"
    id: clockos_switch_rumble_enabled
    restore_mode: RESTORE_DEFAULT_ON
    lambda: |-
      return id(clockos_global_rumble_enabled);
    turn_on_action:
      - lambda: 'id(clockos_global_rumble_enabled) = true;'
    turn_off_action:
      - lambda: 'id(clockos_global_rumble_enabled) = false;'

################################################################
# Output / Display
################################################################
i2c:
  sda: ${clockos_pin_display_sda}
  scl: ${clockos_pin_display_scl}
  frequency: 800kHz

display:
  - platform: ${clockos_display_platform}
    id: clockos_display
    model: ${clockos_display_model}
    address: 0x3C
    invert: false
    contrast: 50%
    auto_clear_enabled: true
    update_interval: 16ms


################################################################
# Input / Encoder
################################################################
sensor:
  - platform: rotary_encoder
    id: clockos_knob
    name: "Knob"
    internal: true
    pin_a:
      number: ${clockos_pin_encoder_a}
      inverted: true
      mode:
        input: true
        pullup: true
    pin_b:
      number: ${clockos_pin_encoder_b}
      inverted: true
      mode:
        input: true
        pullup: true
    on_anticlockwise:
      - script.execute: script_update_last_activity
      - display_menu.up: clockos_menu_main
      - lambda: 'id(clockos_global_knob_direction) = -1;'
    on_clockwise:
      - script.execute: script_update_last_activity
      - display_menu.down: clockos_menu_main
      - lambda: 'id(clockos_global_knob_direction) = 1;'
    min_value: 0
    max_value: 50


################################################################
# Input / Encoder button
################################################################
binary_sensor:
  - platform: gpio
    id: clockos_select_button
    name: "Knob Button"
    internal: true
    pin:
      number: ${clockos_pin_select_button}
      mode: INPUT_PULLUP
      inverted: True
    filters:
    - delayed_on: 10ms
    on_press:
      # Handle knob button press for menu navigation
      then:
        - if:
            condition:
              # If the main menu is already active (i.e., we're navigating within it)
              - display_menu.is_active: clockos_menu_main
            then:
              # Enter (or select the current item) in the main menu
              - display_menu.enter: clockos_menu_main
            else:
              if:
                condition:
                  # Check that knob button isn't handled already
                  - lambda: 'return !id(clockos_global_knob_press_handled);'
                then:
                  - display_menu.show: clockos_menu_main
                  - lambda: id(clockos_output_rumble).turn_off();
                else:
                  - lambda: 'id(clockos_global_knob_pressed) = true;'
        - script.execute: script_update_last_activity

    on_double_click:
      - lambda: 'id(clockos_global_knob_pressed) = false; id(clockos_global_knob_press_handled) = false;'
      - display_menu.hide: clockos_menu_main
      - display.page.show: clockos_page_main
