globals:
  # Keep track of Wi-Fi state
  - id: clockos_global_wifi_enabled
    type: bool
    initial_value: 'true'
    restore_value: yes

# Enable or disable Wi-Fi on boot based on persisted global
esphome:
  on_boot:
    priority: -1000
    then:
      - if:
          condition:
            lambda: 'return id(clockos_global_wifi_enabled);'
          then:
            - lambda: 'ESP_LOGI("system", "Enabling Wi-Fi on boot as per persisted setting");'
            - wifi.enable
          else:
            - lambda: 'ESP_LOGI("system", "Disabling Wi-Fi on boot as per persisted setting");'
            - wifi.disable

display:
  - id: !extend clockos_display
    pages:
      - id: clockos_page_feature_system
        lambda: !include "system.cpp"
      - id: clockos_page_feature_system_info
        lambda: !include "system_info.cpp"


# Factory reset switch
switch:
  - platform: factory_reset
    name: "Factory Reset"
    id: clockos_switch_factory_reset


# Example configuration entry
button:
  - platform: factory_reset
    name: Restart with Factory Default Settings
    id: clockos_feature_system_button_factory_reset

script:
  - id: script_feature_system_start_wifi_setup
    then:
      - logger.log: "Starting Wi-Fi setup mode..."
      - wifi.disable
      - button.press: clockos_feature_system_button_factory_reset
      - button.press: clockos_button_restart


graphical_display_menu:
  id: clockos_menu_main
  items:
    - type: menu
      text: ' System ⏵ '
      items:
        - type: back
          text: ' ⏴ Back '
        - type: command
          text: ' Status '
          on_value:
            then:
                - display_menu.hide: clockos_menu_main
                - display.page.show: clockos_page_feature_system
        - type: command
          text: !lambda |-
            return std::string(" Wifi [") + (!id(clockos_wifi).is_disabled() ? "ON" : "OFF") + "]";
          on_value:
            then:
              - if:
                  condition:
                    lambda: 'return !id(clockos_wifi).is_disabled();'
                  then:
                    - lambda: 'id(clockos_global_wifi_enabled) = false;'
                    - wifi.disable
                  else:
                    - lambda: 'id(clockos_global_wifi_enabled) = true;'
                    - wifi.enable
        - type: command
          text: ' Info '
          on_value:
            then:
                - display_menu.hide: clockos_menu_main
                - display.page.show: clockos_page_feature_system_info
        - type: command
          text: " Restart "
          on_value:
            then:
              - logger.log: "Restarting ClockOS..."
              - delay: 100ms
              - button.press: clockos_button_restart
        - type: menu
          text: " Factory Reset "
          items:
            - type: back
              text: ' ⏴ Back '
            - type: command
              text: " Confirm Reset? "
              on_value:
                then:
                  - script.execute: script_feature_system_start_wifi_setup
